### ISSUE TITLE
`registerSpace` function not found - from README instructions

### ISSUE THREAD

**Issue by orpheuslummis** [web3-storage/w3up#1212]
I'm trying to use w3up for a project following these instructions: https://github.com/web3-storage/w3up/tree/main/packages/w3up-client.
I've obtained`registerSpace` function not found.
(I've also obtained other errors...)
```[tasklist]
### Tasks
- [ ] https://github.com/web3-storage/w3up/pull/1214
- [ ] @orpheuslummis to try out https://web3.storage/docs/w3up-client/#create-and-provision-a-space
```

**Comment by gobengo** [comment]
@orpheuslummis Hey there. Thanks for reporting this. The `registerSpace` method on the client was recently removed in the latest major version of the library, but we forgot to update the README! I just removed mention of `registerSpace` via #1214 and created this for further corrections of the README https://github.com/web3-storage/w3up/issues/1215

The best docs to use for this right now are:
* guide: https://web3.storage/docs/w3up-client/#create-and-provision-a-space
* reference api docs for the w3up Client class: https://web3-storage.github.io/w3up/classes/_web3_storage_w3up_client.Client.html

**Comment by gobengo** [comment]
@orpheuslummis I'm going to close this in hopes we've resolve the issue, but feel free to reopen it if you'd like to keep discussing it
