### ISSUE TITLE
Fix type error in `createDelegation` within JS client

### ISSUE THREAD

**Issue by salieflewis** [web3-storage/w3up#1250]
When implementing the following lines of code as shown in the [Delegated](https://web3.storage/docs/concepts/architecture-options/) example, typescript complains the type of the abilities string array does not match with the expected type.

```
const abilities = ['upload/add', 'store/add']
const delegation = await client.createDelegation(audience, abilities)
```

cc: @travis

**Comment by alanshaw** [comment]
@salieflewis you should be able to do this now to resolve those type errors:

```js
import { asAbilities } from '@web3-storage/w3up-client'

const abilities = asAbilities(['upload/add', 'store/add'])
const delegation = await client.createDelegation(audience, abilities)
```

Shout if you find it not working properly.
