### ISSUE TITLE
voucher/* stuff does not follow the spec

### ISSUE THREAD

**Issue by Gozala** [web3-storage/w3up#162]
Current implementation of `vourcher/*` capabilities does not [follow the spec](https://hackmd.io/@gozala/w3-accounts). Maybe things have been changed deliberately, or perhaps it was mistake. I would like to know which one and either update the implementation or a spec.

**Comment by hugomrdias** [comment]
I tweaked some things to be more readable (like the nb fields) and to be able to ship something usable. 
We can discuss and adjust further to reconcile.

**Comment by hugomrdias** [comment]
can we move discussion to https://github.com/web3-storage/specs/pull/5 ?
