### ISSUE TITLE
access-api sentry logs should show stack traces that are sourcemap-aware

### ISSUE THREAD

**Issue by gobengo** [web3-storage/w3up#367]
Context
* this is not urgent, but would aid in debugging
* when access-api errors in production, the stack traces don't seem to be sourcemap-aware
  * [example error stack message in response body](https://github.com/web3-storage/w3protocol/issues/363)
  * [same-ish error in sentry](https://sentry.io/organizations/protocol-labs-it/issues/3883075975/?query=is%3Aunresolved&referrer=issue-stream)
* stack ends up like
```
#     stack: 'HTTPError: HTTP Request failed\\n' +
#       '    at lN.throw (d1-beta-facade.entry.js:14585:11)\\n' +
#       '    at dN.request (d1-beta-facade.entry.js:14579:135)\\n' +
#       '    at async WN (d1-beta-facade.entry.js:15030:45)\\n' +
#       '    at async Object. (d1-beta-facade.entry.js:15037:132)\\n' +
#       '    at async IB (d1-beta-facade.entry.js:14077:12)\\n' +
#       '    at async AB (d1-beta-facade.entry.js:14065:12)\\n' +
#       '    at async TB (d1-beta-facade.entry.js:14059:42)\\n' +
#       '    at async PO (d1-beta-facade.entry.js:15097:11)\\n' +
#       '    at async ed.fetch (d1-beta-facade.entry.js:9434:17)\\n' +
#       '    at async Object.fetch (d1-beta-facade.entry.js:20183:13)',
```

Desired Behavior
* the stack traces in sentry use non-minified variable names, and have sourcemap-aware file paths, not `d1-beta-facade.entry.js`

**Comment by gobengo** [comment]
@hugomrdias any ideas on path forward on this? I see in the build script some sourcemap-related stuff is already enabled, and [these cloudflare docs]() aren't very detailed.

Could it be just that we need our release script to have `process.env.SENTRY_UPLOAD === 'true'`?
https://github.com/web3-storage/w3protocol/blob/main/packages/access-api/scripts/cli.js#L77

**Comment by hugomrdias** [comment]
this is related to D1 check this PR

**Comment by gobengo** [comment]
Will work on this at https://github.com/web3-storage/w3up/issues/623
