### ISSUE TITLE
access-api stacktraces in sentry are not working

### ISSUE THREAD

**Issue by vasco-santos** [web3-storage/w3up#623]

**Comment by gobengo** [comment]
related: https://github.com/web3-storage/w3protocol/issues/367

**Comment by gobengo** [comment]
As long as we use d1 which requires `no_bundle=false` (or omitted) in wrangler.toml, I think we'd have to do something like this which pushes source maps to sentry via sentry-cli in our deploy pipeline. https://github.com/robertcepa/toucan-js/tree/master/examples/wrangler-basic#wrangler-basic-starter

**Comment by gobengo** [comment]
I just learned some things:
* there is already some support in the access-api build script to upload the source maps to sentry: https://github.com/web3-storage/w3up/blob/main/packages/access-api/scripts/cli.js#L77
* afaict, `process.env.SENTRY_UPLOAD === 'true'` is true in the github actions that deploy to staging and production. e.g. [this sample deploy seems to have created a release in sentry](https://github.com/web3-storage/w3up/actions/runs/4621902418/jobs/8173939598#step:8:188)
* I see source maps for recent releases in staging and production in the [source maps](https://protocol-labs-it.sentry.io/settings/projects/w3access-api/source-maps/?cursor=10%3A1%3A0&query=&sort=-date_added) settings for access-api in our sentry
* I see [releases](https://protocol-labs-it.sentry.io/releases/?cursor=20%3A0%3A1&project=6536511&sort=date) in sentry from latest deploys
* and [recent errors](https://protocol-labs-it.sentry.io/issues/4030779960/?environment=production&project=6536511&query=is%3Aunresolved&referrer=issue-stream&stream_index=1) seem to show like `release: 5.2.1-production (a4d3409)`
  * So I was surprised that error still doesn't have very much help from source maps.

I noticed this issue https://github.com/web3-storage/w3up/issues/254
mentions upgrading toucan-js, which is the sentry library that access-api uses.
* that [3.0.0 release](https://github.com/robertcepa/toucan-js/releases)
    > This is a complete rewrite of toucan-js. The goal of this update is to reuse more components from [@sentry/core](https://github.com/getsentry/sentry-javascript/tree/master/packages/core), **fix long-standing issues with source maps**, and provide starters using various bundlers (esbuild, rollup, vite, webpack).
* mentions source maps, seems worth trying
* rn access-api [uses toucan-js ^2.7.0](https://github.com/web3-storage/w3up/blob/main/packages/access-api/package.json#L41), so we aren't yet using the latest and greatest source maps stuff.

So what I will try is upgrading toucan-js to >= 3.x, as suggested by #254

**Comment by gobengo** [comment]
* [ ] need to upgrade `@web3-storage/worker-utils` toucan version as well  https://github.com/web3-storage/workers/issues/20

**Comment by gobengo** [comment]
* I deployed the toucan-js@3.x upgrade to access-api staging env
* triggered error on staging using w3cli `W3_UPLOAD_SERVICE_DID='did:web:staging.web3.storage' W3_UPLOAD_SERVICE_URL='https://staging.up.web3.storage/' W3_ACCESS_SERVICE_DID='did:web:staging.web3.storage' W3_ACCESS_SERVICE_URL='https://w3access-staging.protocol-labs.workers.dev' DEBUG='*' ./shim.js authorize "example@example.com"`
  * `example@example.com` leads to an error (useful here)
  * [error in sentry](https://protocol-labs-it.sentry.io/issues/4067812915/?environment=staging&project=6536511&query=&referrer=issue-stream&statsPeriod=14d&stream_index=0)
    * no stack traces :/ (beyond showing `export default worker` like before)
    * but I also see a 'Tell us where your source code is' link on that. It asked me to give it a github url to '../src/index.js', so I did `https://github.com/web3-storage/w3up/blob/main/packages/access-api/src/index.js`
<img width="629" alt="Screenshot 2023-04-06 at 1 05 27 PM" src="https://user-images.githubusercontent.com/171782/230483157-2bca4af1-66e5-4a03-8cf0-c3625d4fdd2b.png">
    * sentry didn't know about the w3up repo, so I added it https://protocol-labs-it.sentry.io/settings/integrations/github/109727/
    * It made 'open this line with github' work, but it still just takes you to the line for `export default worker`

**Comment by gobengo** [comment]
I've been trying to figure out what to try next, and just noticed:
* the sentry [error](https://protocol-labs-it.sentry.io/issues/4067812915/?environment=staging&project=6536511&query=is%3Aunresolved&referrer=issue-stream&stream_index=0) still doesn't have a source-map aware stack trace
* says `6.0.0-staging (99c532a)` [url](https://protocol-labs-it.sentry.io/releases/%40web3-storage__access-api%406.0.0-staging%2B99c532a/?project=6536511)
  * in sentry, that release exists and does have 2 source map artifacts
* what does that sha `99c532a` in the release correspond to?
  * if I make a github url for it, something loads https://github.com/web3-storage/w3up/commit/99c532a but it says "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." 
* theory:
  * the staging release happens from [branch](https://github.com/web3-storage/w3up/commits/release-please--branches--main--components--access-api) `release-please--branches--main--components--access-api` managed by release-please-action
  * It appears release-please action, doesn't append new commits to that branch, it force-pushes a new one and removes the old one

**Comment by gobengo** [comment]
oooh I should try what @olizilla did here
https://github.com/web3-storage/web3.storage/pull/1033/files#diff-fcc5ef774a5ba3602a1c3478168015fa7b4b4b154887b7d2ed197720f65501f1R57

(It's funny, I was reading this toucan-js issue thread and organically stumbled upon an @olizilla https://github.com/robertcepa/toucan-js/issues/54#issuecomment-930416972 )

**Comment by gobengo** [comment]
I should also try not using `rewriteFrames` as suggested https://github.com/robertcepa/toucan-js/issues/54#issuecomment-1338937523

**Comment by gobengo** [comment]
I wondered if any part of it was due to the way I was triggering the error that got into sentry, which was a ucanto `HandlerExecutionError`. (I was thinking maybe someone needed to call `Error.captureStackTrace()`, I don't think that's needed the way ucanto subclasses `Error`).

So I added a simple route that will throw an error (as oli had done while testing this type of thing).
That produced [this error](https://protocol-labs-it.sentry.io/issues/4071137081/?query=is%3Aunresolved&referrer=issue-stream&stream_index=0) but did not affect stack trace rendering. :|

**Comment by gobengo** [comment]
* [ ] try using `@sentry/esbuild-plugin` to send the source maps https://github.com/robertcepa/toucan-js/blob/master/examples/wrangler-esbuild/esbuild.config.js#L15
  * pro: it's what toucan-js 3.0.0 examples use, so it's likely to get the most support from @robertcepa if we followup on [this past help](https://github.com/robertcepa/toucan-js/issues/54#issuecomment-1338937523)
  * con: it's not what our other services do (afiact), so it's making things less like our other services.
    * Though those other services use toucan-js 2.7.0 anyway. so if we scout out a way that works with toucan-js 3.0.0, maybe those other services would benefit
* [ ] meet with @olizilla to brainstorm which other things to try

**Comment by gobengo** [comment]
* [ ] try not sending source maps as part of CI, and just using the source maps generated by cloudflare bundle (`no_bundle=false`) which seems same as [wrangler-basic starter](https://github.com/robertcepa/toucan-js/tree/master/examples/wrangler-basic)
  * [x] removed staging env var `SENTRY_UPLOAD` to test, [re-ran deploy staging job](https://github.com/web3-storage/w3up/actions/runs/4642734873)
* [ ] ask for help on sentry support
* [ ] ask for help on toucan-js issues
