### ISSUE TITLE
Type mismatch between setCurrentSpace() and space.did()

### ISSUE THREAD

**Issue by nessup** [web3-storage/w3up#681]
There is a minor mismatch between the string type expected by setCurrentSpace() and space.did(). The former expects `did:key:${string}`, while the latter returns `did:${string}:${string}`

![image](https://user-images.githubusercontent.com/1820695/227379234-e043aa3b-f705-42ec-abd1-80fdadbd7a0c.png)

**Comment by gobengo** [comment]
@nessup This was an accidental change to the types here. I [changed it back to allow `did:${string}:${string}`](https://github.com/web3-storage/w3up/pull/669#discussion_r1151248241) which released as `@web3-storage/w3up-client@5.5.0`. 

In general, though, right now space DIDs are always `did:key:${string}`. If you ever have a broader type, you may need to use a [type assertion](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions) or other [narrowing](https://www.typescriptlang.org/docs/handbook/2/narrowing.html) technique.

For DIDs, we usually type as
```
Ucanto.DID // any did, similar to `did:${string}:${string}`
Ucanto.DID<MethodType> // specific did methods, similar to `did:${Method}:${string}`
Ucanto.DID<'key'> // `did:key:...` did
Ucanto.DID<'key'|'web'> // `did:key:${string}` or `did:web:${string}`
```

I'm hoping one of the above bits of info can help resolve this issue, but if it doesn't, please reopen and we'll try to resolve another way.
