### ISSUE TITLE
Error: Cannot find module './fetch.node' when running example

### ISSUE THREAD

**Issue by CluEleSsUK** [web3-storage/w3up#828]
I'm getting the error in the title when running the example from [here](https://blog.web3.storage/posts/introducing-w3up).

The stacktrace points to `node_modules/ipfs-utils/src/http/fetch.js `

I'm running on node `v19.4.0` which has fetch builtin.

Interestingly, running my code in ts-node throws:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /some/path/to/node_modules/@web3-storage/w3up-client/src/index.node.js from /some/path/to/node_modules/src/index.ts not supported.
Instead change the require of index.node.js in /some/path/to/node_modules/src/index.ts to a dynamic import() which is available in all CommonJS modules.
```

I have tried making my project a module, tried changing the tsconfig to output `esnext` and `commonjs` style modules, to no avail.

In case it's relevant, I'm using `esbuild` like so:
```esbuild ./src/index.ts --bundle --platform=node --target=node19 --outfile=index.js``` and running with `node ./index.js`

**Comment by CluEleSsUK** [comment]
Unrelated, but neither the `files-from-path` example nor the install commands on the example work out-of-the-box.
The former has changed their exported func name to `filesFromPaths` from `getFilesFromPath`, and the w3up client has moved its package.

**Comment by Honour-d-dev** [comment]
Hi, did you find a fix??
