### ISSUE TITLE
service does not implement {can: "voucher/claim"} when calling registerSpace

### ISSUE THREAD

**Issue by gotjoshua** [web3-storage/w3up#888]
service does not implement {can: "voucher/claim"} handlerjcapability�ccanmvoucher/claimdwithx8did:key
any help?

**Comment by travis** [comment]
hi there - this should be fixed by uploading to the latest version of the client - could you tell me more about how you're calling `registerSpace`?

**Comment by tennox** [comment]
We're using the latest versions as far as I [can tell](https://github.com/web3-storage/w3ui/releases)
```
@w3ui/keyring-core 5.0.0
@w3ui/uploader-core 6.0.0
```

We're using code based on your solid components, which reproducibly have this error - I have created another issue with more details here:
https://github.com/web3-storage/w3ui/issues/545

**Comment by travis** [comment]
ok we tracked this down to a misbuilt package - I've released a new version of `keyring-core` and its dependencies that should fix this! please reopen if you're still running into problems.
